spring.application.name=biblioteca
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# setup connessione database
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:biblioteca_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:root}

# configurazioni per JPA
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true

# configurazioni del framework (impostazione su redirect)
server.forward-headers-strategy=framework

# swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# logging di base
logging.level.root=INFO