spring.jpa.show-sql=false
logging.level.root=INFO
logging.file.name=/var/log/biblioteca/app.log
logging.logback.rollingpolicy.file-name-pattern=/var/log/biblioteca/app-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=5
